"""
VacinaFácil AI — Adiciona vacinas faltantes ao banco
Expande de 22 → 35 vacinas cobrindo o PNI 2024 + rede privada relevante
Uso: python adicionar_vacinas.py
"""

import os
from dotenv import load_dotenv
from supabase import create_client

load_dotenv(override=True)
supabase = create_client(os.getenv("SUPABASE_URL"), os.getenv("SUPABASE_SERVICE_KEY"))

VACINAS_NOVAS = [
    {
        "id": "VAC023",
        "nome_da_vacina": "Poliomielite Oral (VOP)",
        "nome_popular_apelido": "Gotinha da Polio, Vacina Oral da Pólio",
        "sinonimos_variacoes": "VOP, vacina oral pólio, gotinha, bOPV, pólio oral, poliomielite oral",
        "doencas_prevenidas": "Poliomielite (paralisia infantil)",
        "tipo_de_vacina": "Vírus atenuado oral",
        "publico_alvo": "Crianças de 15 meses e 4 anos (reforços do esquema)",
        "faixa_etaria_recomendada": "15 meses (1º reforço) e 4 anos (2º reforço)",
        "idade_da_1a_dose": "15 meses (como reforço — doses iniciais são VIP injetável)",
        "doses_totais_padrao": "2 doses (reforços)",
        "esquema_resumido": "1º reforço: 15 meses | 2º reforço: 4 anos. As doses iniciais (2, 4 e 6 meses) usam VIP injetável (VAC007).",
        "tipo_de_esquema": "Reforço oral — complementa o esquema VIP",
        "intervalo_entre_doses": "Mínimo de 6 meses entre os reforços",
        "via_de_administracao": "Oral (gotas)",
        "local_de_aplicacao_no_corpo": "Boca (2 gotas)",
        "disponivel_no_sus": "Sim",
        "disponivel_na_rede_privada": "Não (exclusiva do SUS)",
        "onde_se_vacinar": "UBS (Unidade Básica de Saúde)",
        "obrigatoria": "Sim (Calendário PNI)",
        "calendario_pni": "Calendário da Criança — reforços aos 15 meses e 4 anos",
        "contraindicacoes": "Imunodeficiência grave (usar VIP); crianças com HIV sintomático; contato domiciliar com imunodeprimido grave",
        "precaucoes": "Adiar em caso de diarreia intensa ou vômitos",
        "efeitos_colaterais_comuns": "Muito raramente: paralisia associada à vacina (VAPP) — risco muito baixo, 1 caso por ~2,4 milhões de doses",
        "restricoes_para_gestantes": "Contraindicada na gestação por precaução (usar VIP se necessário)",
        "restricoes_para_imunossuprimidos": "Contraindicada — usar VIP injetável",
        "eficacia_descritiva": "Altamente eficaz como reforço; combinada com VIP oferece proteção de intestino, reduzindo transmissão comunitária",
        "duracao_da_protecao": "Longa duração (anos)",
        "palavras_chave_ia": "gotinha pólio, vacina oral poliomielite, VOP, reforço pólio, paralisia infantil gotinha, poliomielite oral criança",
        "perguntas_gatilho_ia": "Meu filho precisa da gotinha? Qual é a diferença entre gotinha e injetável da pólio? Meu filho já tomou VIP precisa da gotinha?",
        "resposta_padrao_sugerida": "A gotinha da pólio (VOP) é usada como reforço aos 15 meses e 4 anos no calendário do SUS, enquanto as doses iniciais (2, 4 e 6 meses) são a VIP injetável. As duas juntas garantem proteção completa contra a paralisia infantil.",
        "mitos_comuns": "A gotinha causa paralisia; a injetável é melhor que a gotinha",
        "resposta_a_mitos": "A paralisia associada à VOP é extremamente rara (1 caso em milhões de doses). O Brasil usa as duas vacinas de forma complementar — VIP para doses iniciais e VOP para reforços — seguindo a recomendação da OMS.",
        "status_de_revisao": "Revisado",
        "disponivel_no_sus": "Sim",
    },
    {
        "id": "VAC024",
        "nome_da_vacina": "Pneumocócica 13-valente (PCV13)",
        "nome_popular_apelido": "Prevnar 13, pneumo 13",
        "sinonimos_variacoes": "PCV13, Prevnar 13, vacina pneumocócica conjugada 13, pneumo conjugada 13 valente",
        "doencas_prevenidas": "Pneumonia, meningite, otite e sepse causadas por 13 sorotipos do Streptococcus pneumoniae",
        "tipo_de_vacina": "Polissacarídeo conjugado",
        "publico_alvo": "Imunodeprimidos, transplantados, HIV+, asplênicos; crianças e adultos em situações especiais via CRIE",
        "faixa_etaria_recomendada": "Lactentes a adultos — conforme indicação clínica",
        "doses_totais_padrao": "Crianças < 1 ano: 3 doses + reforço; > 2 anos e adultos: 1-2 doses (conforme situação clínica)",
        "esquema_resumido": "Lactentes: 2, 4, 6 meses + reforço 12-15 meses | Adultos imunodeprimidos: 1 dose PCV13 seguida de PPV23",
        "disponivel_no_sus": "Sim, via CRIE (Centro de Referência para Imunobiológicos Especiais) para grupos de risco",
        "disponivel_na_rede_privada": "Sim",
        "onde_se_vacinar": "CRIE para grupos de risco; clínicas particulares para demais",
        "contraindicacoes": "Hipersensibilidade a componentes da vacina ou à difteria toxoide",
        "efeitos_colaterais_comuns": "Dor local, vermelhidão, inchaço no local da injeção; febre baixa; irritabilidade",
        "restricoes_para_gestantes": "Dados limitados; usar somente se claramente necessário — avaliar com médico",
        "restricoes_para_imunossuprimidos": "Pode ser usada (vacina inativada); sequência recomendada: PCV13 → PPV23 (intervalo ≥ 8 semanas)",
        "eficacia_descritiva": "Previne pneumonia invasiva por pneumococo com eficácia >70% em crianças; 45-75% em adultos >65 anos",
        "palavras_chave_ia": "PCV13, prevnar 13, pneumo 13, pneumococo 13 sorotipos, CRIE pneumococo, imunodeprimido pneumonia",
        "perguntas_gatilho_ia": "Qual a diferença entre a pneumo 10 e pneumo 13? Imunodeprimido precisa de qual pneumococo? Meu filho com HIV precisa de vacina pneumocócica especial?",
        "resposta_padrao_sugerida": "A PCV13 (Prevnar 13) é indicada principalmente para imunodeprimidos, HIV positivos, transplantados e asplênicos via CRIE. Para crianças saudáveis, o SUS oferece a PCV10. Consulte o CRIE mais próximo se você se enquadra nos grupos de risco.",
        "status_de_revisao": "Revisado",
    },
    {
        "id": "VAC025",
        "nome_da_vacina": "Herpes Zóster (Shingrix)",
        "nome_popular_apelido": "Vacina do cobreiro, Shingrix, vacina zóster recombinante",
        "sinonimos_variacoes": "Shingrix, RZV, zóster recombinante adjuvantada, cobreiro vacina, herpes zoster vacina",
        "doencas_prevenidas": "Herpes zóster (cobreiro) e neuralgia pós-herpética",
        "tipo_de_vacina": "Subunidade recombinante adjuvantada (não contém vírus vivo)",
        "publico_alvo": "Adultos ≥ 50 anos; adultos ≥ 18 anos imunodeprimidos",
        "faixa_etaria_recomendada": "A partir dos 50 anos (população geral); a partir dos 18 anos para imunodeprimidos",
        "idade_da_1a_dose": "50 anos",
        "doses_totais_padrao": "2 doses",
        "doses_totais_imunossuprimido": "2 doses",
        "esquema_resumido": "2 doses com intervalo de 2 a 6 meses",
        "intervalo_entre_doses": "2 a 6 meses entre as doses",
        "via_de_administracao": "Intramuscular (IM)",
        "local_de_aplicacao_no_corpo": "Deltóide (músculo do braço)",
        "disponivel_no_sus": "Não (disponível apenas na rede privada)",
        "disponivel_na_rede_privada": "Sim",
        "onde_se_vacinar": "Clínicas de vacinação particulares",
        "obrigatoria": "Não",
        "contraindicacoes": "Hipersensibilidade grave a qualquer componente; não indicada durante gravidez",
        "precaucoes": "Adiar em caso de doença aguda grave com febre; não administrar em imunossupressão severa ativa (iniciar após estabilização)",
        "efeitos_colaterais_comuns": "Dor no local (muito frequente >80%), vermelhidão, inchaço; fadiga, cefaleia, calafrios, febre, mialgia nos primeiros dias — efeitos do adjuvante AS01B, passageiros",
        "efeitos_colaterais_raros_graves": "Anafilaxia (muito rara)",
        "restricoes_para_gestantes": "Contraindicada na gravidez — vacinar após o parto",
        "restricoes_para_imunossuprimidos": "Pode ser usada (é inativada); indicada para imunodeprimidos ≥ 18 anos — verificar com médico o momento ideal",
        "eficacia_numerica": 97,
        "eficacia_descritiva": "97% de eficácia em adultos ≥ 50 anos saudáveis; 68-91% em imunodeprimidos; reduz drasticamente a neuralgia pós-herpética",
        "duracao_da_protecao": "≥ 10 anos (estudos em andamento sugerem proteção duradoura)",
        "mitos_comuns": "Quem já teve cobreiro não precisa vacinar; a vacina pode causar cobreiro; já tomei a vacina de catapora não preciso",
        "resposta_a_mitos": "Quem já teve cobreiro PODE e DEVE vacinar — nova infecção é possível. Shingrix não contém vírus vivo, portanto não causa cobreiro. A vacina de varicela (catapora) não protege contra recorrência do vírus já latente no organismo.",
        "palavras_chave_ia": "cobreiro vacina, herpes zoster vacina, Shingrix, neuralgia pos-herpetica, vacina idoso cobreiro, 50 anos cobreiro",
        "perguntas_gatilho_ia": "Existe vacina para cobreiro? Posso tomar vacina do cobreiro? Quem já teve cobreiro precisa de vacina? Shingrix tem no SUS?",
        "resposta_padrao_sugerida": "Sim, existe vacina para o cobreiro — Shingrix. São 2 doses com 2 a 6 meses de intervalo. É recomendada para maiores de 50 anos e imunodeprimidos a partir de 18 anos. Não está disponível no SUS, somente em clínicas particulares.",
        "status_de_revisao": "Revisado",
    },
    {
        "id": "VAC026",
        "nome_da_vacina": "Meningocócica B (MenB)",
        "nome_popular_apelido": "Bexsero, vacina meningite B, MenB",
        "sinonimos_variacoes": "Bexsero, MenB, meningocócica B, vacina meningite B, 4CMenB",
        "doencas_prevenidas": "Meningite e meningococcemia por Neisseria meningitidis sorogrupo B",
        "tipo_de_vacina": "Subunidade proteica recombinante",
        "publico_alvo": "Lactentes a adultos; SBIm recomenda a partir dos 3 meses",
        "faixa_etaria_recomendada": "A partir de 3 meses de idade",
        "doses_totais_padrao": "3 doses (3-5 meses) + reforço; 2 doses (6-11 meses); 2 doses (≥ 12 meses e adultos)",
        "esquema_resumido": "< 6 meses: 3 doses + reforço | 6-11 meses: 2 doses + reforço | ≥ 1 ano e adultos: 2 doses (intervalo 1-2 meses)",
        "intervalo_entre_doses": "1 a 2 meses entre doses",
        "via_de_administracao": "Intramuscular (IM)",
        "local_de_aplicacao_no_corpo": "Coxa (lactentes); deltóide (crianças e adultos)",
        "disponivel_no_sus": "Não (disponível apenas na rede privada)",
        "disponivel_na_rede_privada": "Sim",
        "onde_se_vacinar": "Clínicas de vacinação particulares",
        "obrigatoria": "Não (recomendação SBIm, fora do PNI rotina)",
        "contraindicacoes": "Hipersensibilidade a componentes",
        "efeitos_colaterais_comuns": "Dor, vermelhidão e inchaço no local; febre (especialmente em lactentes); irritabilidade; sonolência",
        "restricoes_para_gestantes": "Dados limitados; usar somente se benefício superar risco — avaliar com médico",
        "eficacia_descritiva": "~73-80% contra cepas B correspondentes em estudos populacionais; eficácia variável conforme cepa circulante",
        "palavras_chave_ia": "meningite B vacina, Bexsero, MenB, meningococo B, sorogrupo B meningite",
        "perguntas_gatilho_ia": "Existe vacina para meningite B? Bexsero tem no SUS? Meu filho precisa da MenB? Qual é a vacina de meningite B?",
        "resposta_padrao_sugerida": "A vacina contra meningococo B (Bexsero) não está no calendário do SUS — é disponível apenas em clínicas particulares. A SBIm recomenda para crianças a partir de 3 meses. O SUS oferece proteção contra os sorogrupos C (VAC010) e ACWY (VAC018).",
        "status_de_revisao": "Revisado",
    },
    {
        "id": "VAC027",
        "nome_da_vacina": "HPV 9-valente (Gardasil 9)",
        "nome_popular_apelido": "Gardasil 9, HPV nonavalente, HPV 9",
        "sinonimos_variacoes": "Gardasil 9, nonavalente HPV, HPV 9 cepas, 9vHPV",
        "doencas_prevenidas": "Câncer de colo do útero, vulvar, vaginal, anal, orofaríngeo e verrugas genitais causados por 9 tipos de HPV (6, 11, 16, 18, 31, 33, 45, 52, 58)",
        "tipo_de_vacina": "Partícula semelhante a vírus (VLP) recombinante",
        "publico_alvo": "Meninas e meninos de 9 a 45 anos",
        "faixa_etaria_recomendada": "9 a 45 anos",
        "doses_totais_padrao": "2 doses (9-14 anos); 3 doses (15-45 anos)",
        "esquema_resumido": "9-14 anos: 2 doses (0 e 6 meses) | 15-45 anos: 3 doses (0, 2 e 6 meses)",
        "intervalo_entre_doses": "2 meses entre 1ª e 2ª dose; 4 meses entre 2ª e 3ª dose (esquema de 3 doses)",
        "via_de_administracao": "Intramuscular (IM)",
        "local_de_aplicacao_no_corpo": "Deltóide",
        "disponivel_no_sus": "Não — o SUS oferece a quadrivalente (4 cepas: VAC002); a 9-valente é somente na rede privada",
        "disponivel_na_rede_privada": "Sim",
        "onde_se_vacinar": "Clínicas de vacinação particulares",
        "contraindicacoes": "Hipersensibilidade a levedura ou componentes; gravidez (adiar até após o parto)",
        "efeitos_colaterais_comuns": "Dor, vermelhidão e inchaço no local; cefaleia; febre",
        "restricoes_para_gestantes": "Contraindicada na gravidez — adiar para após o parto",
        "eficacia_numerica": 97,
        "eficacia_descritiva": "97% de eficácia contra lesões relacionadas aos 9 tipos de HPV incluídos; maior cobertura que a quadrivalente",
        "palavras_chave_ia": "HPV 9 cepas, Gardasil 9, HPV nonavalente, vacina HPV mais completa, HPV privada, 9 tipos HPV",
        "perguntas_gatilho_ia": "Qual a diferença entre a HPV do SUS e a Gardasil 9? HPV 9 valente vale a pena? Posso tomar HPV com mais de 14 anos?",
        "resposta_padrao_sugerida": "A Gardasil 9 protege contra 9 tipos de HPV, enquanto a vacina do SUS (quadrivalente) cobre 4 tipos. A 9-valente oferece proteção mais ampla, mas só está disponível em clínicas particulares. O SUS oferece a quadrivalente gratuitamente para meninas de 9-14 anos e meninos de 11-14 anos.",
        "status_de_revisao": "Revisado",
    },
    {
        "id": "VAC028",
        "nome_da_vacina": "Mpox (Varíola dos Macacos — Jynneos)",
        "nome_popular_apelido": "Vacina mpox, varíola dos macacos vacina, Jynneos, Imvamune",
        "sinonimos_variacoes": "mpox vacina, varíola macacos, Jynneos, Imvamune, vacina MVA-BN",
        "doencas_prevenidas": "Mpox (antiga varíola dos macacos) e varíola humana",
        "tipo_de_vacina": "Vírus vaccinia modificado Ankara (MVA) — vírus vivo não replicativo",
        "publico_alvo": "Grupos de risco: HSH (homens que fazem sexo com homens), trabalhadores do sexo, profissionais de saúde em risco, contatos de casos confirmados",
        "faixa_etaria_recomendada": "18 anos ou mais (grupos de risco)",
        "doses_totais_padrao": "2 doses",
        "esquema_resumido": "2 doses com intervalo de 28 dias | Pós-exposição: 1 dose em até 4 dias do contato",
        "intervalo_entre_doses": "28 dias",
        "via_de_administracao": "Subcutânea (SC) ou intradérmica (ID) — a via ID usa dose menor",
        "local_de_aplicacao_no_corpo": "Braço (região do deltóide)",
        "disponivel_no_sus": "Sim, via CRIE (para grupos de risco específicos — não rotina universal)",
        "disponivel_na_rede_privada": "Disponibilidade limitada",
        "onde_se_vacinar": "CRIE (Centros de Referência para Imunobiológicos Especiais) — procure o CRIE mais próximo",
        "contraindicacoes": "Imunodeficiência severa (avaliação caso a caso); hipersensibilidade a componentes",
        "efeitos_colaterais_comuns": "Dor local, vermelhidão, inchaço; fadiga, cefaleia, mialgia, náusea",
        "restricoes_para_gestantes": "Usar com cautela — avaliar risco/benefício com médico; mpox em gestantes é grave",
        "restricoes_para_imunossuprimidos": "Avaliação individual — vacina não replicativa é mais segura que vacinas replicativas antigas",
        "eficacia_descritiva": "Estimativa de 85% de eficácia na prevenção de mpox em estudos observacionais durante surto de 2022",
        "mitos_comuns": "Mpox é doença só de homossexuais; mpox e varíola são a mesma coisa",
        "resposta_a_mitos": "Mpox pode afetar qualquer pessoa, embora grupos com múltiplos parceiros sexuais tenham maior risco. Mpox e varíola humana são causadas por vírus diferentes; a varíola foi erradicada em 1980.",
        "palavras_chave_ia": "mpox vacina, varíola macacos vacina, CRIE mpox, Jynneos, imunização mpox, vacina viajante mpox",
        "perguntas_gatilho_ia": "Existe vacina para mpox? Onde tomar vacina de varíola dos macacos? Tenho direito à vacina de mpox no SUS?",
        "resposta_padrao_sugerida": "Existe vacina para mpox (Jynneos) disponível no Brasil via CRIE para grupos de risco. São 2 doses com 28 dias de intervalo. Para saber se você tem indicação, procure o CRIE mais próximo ou uma UBS.",
        "status_de_revisao": "Revisado",
    },
    {
        "id": "VAC029",
        "nome_da_vacina": "Nirsevimabe (Beyfortus) — Anticorpo monoclonal RSV",
        "nome_popular_apelido": "Beyfortus, anticorpo RSV, imunização passiva RSV, nirsevimabe",
        "sinonimos_variacoes": "Beyfortus, nirsevimabe, anticorpo monoclonal RSV, imunização passiva vírus sincicial, RSV recém-nascido",
        "doencas_prevenidas": "Doença grave por Vírus Sincicial Respiratório (VSR/RSV) — bronquiolite e pneumonia em lactentes",
        "tipo_de_vacina": "Anticorpo monoclonal de longa ação (não é vacina convencional — é imunização passiva)",
        "publico_alvo": "Recém-nascidos e lactentes até 12 meses; crianças de 12-24 meses com condições de risco (cardiopatia congênita, doença pulmonar crônica, imunocomprometimento)",
        "faixa_etaria_recomendada": "0 a 12 meses (e até 24 meses em grupos de risco)",
        "doses_totais_padrao": "1 dose única",
        "esquema_resumido": "1 dose única IM antes ou durante a temporada de VSR (outono/inverno)",
        "via_de_administracao": "Intramuscular (IM)",
        "local_de_aplicacao_no_corpo": "Coxa (músculo vasto lateral)",
        "disponivel_no_sus": "Em processo de incorporação ao PNI — verificar atualização mais recente",
        "disponivel_na_rede_privada": "Sim",
        "onde_se_vacinar": "Clínicas particulares; quando incorporado ao PNI, será na UBS",
        "contraindicacoes": "Hipersensibilidade conhecida ao nirsevimabe",
        "efeitos_colaterais_comuns": "Dor, vermelhidão no local da injeção; febre; irritabilidade",
        "restricoes_para_gestantes": "Não se aplica (é administrado no bebê, não na mãe)",
        "eficacia_numerica": 75,
        "eficacia_descritiva": "75% de redução em hospitalizações por VSR; 83% de redução de casos graves",
        "palavras_chave_ia": "Beyfortus, nirsevimabe, RSV bebe, vírus sincicial respiratório, bronquiolite vacina, anticorpo RSV recem nascido",
        "perguntas_gatilho_ia": "Existe vacina para bronquiolite? O que é Beyfortus? Meu bebê precisa de anticorpo contra RSV? Vírus sincicial tem vacina?",
        "resposta_padrao_sugerida": "O Beyfortus (nirsevimabe) não é uma vacina convencional, mas um anticorpo pronto que protege bebês contra RSV (vírus sincicial respiratório), principal causa de bronquiolite grave. É 1 dose única para bebês de até 12 meses, disponível em clínicas particulares e em processo de incorporação ao SUS.",
        "status_de_revisao": "Revisado",
    },
    {
        "id": "VAC030",
        "nome_da_vacina": "Febre Tifóide (Typhim Vi / Typherix)",
        "nome_popular_apelido": "Vacina tifóide, vacina para febre tifóide, Typhim Vi",
        "sinonimos_variacoes": "tifóide vacina, Typhim Vi, Typherix, Vi-CPS, febre tifoide imunização, tifo vacina",
        "doencas_prevenidas": "Febre tifóide (Salmonella Typhi)",
        "tipo_de_vacina": "Polissacarídeo capsular purificado (Vi-CPS) — injetável; ou atenuada oral (Vivotif) para adultos",
        "publico_alvo": "Viajantes para áreas endêmicas (Ásia, África, América Latina rural); trabalhadores em saneamento e laboratórios; contatos domiciliares de portadores crônicos",
        "faixa_etaria_recomendada": "A partir de 2 anos (injetável); a partir de 6 anos (oral)",
        "doses_totais_padrao": "1 dose (injetável Vi-CPS); 3 doses em dias alternados (oral Vivotif)",
        "esquema_resumido": "Vi-CPS: 1 dose IM pelo menos 2 semanas antes da viagem; reforço a cada 3 anos se risco contínuo",
        "intervalo_entre_doses": "Reforço a cada 3 anos para exposição contínua",
        "via_de_administracao": "Intramuscular (IM) — injetável; Oral — cápsulas",
        "disponivel_no_sus": "Sim, via CRIE para situações especiais (não disponível como rotina em UBS)",
        "disponivel_na_rede_privada": "Sim",
        "onde_se_vacinar": "CRIE (para indicações específicas); clínicas de viagem e vacinação privadas",
        "contraindicacoes": "Hipersensibilidade a componentes; oral: imunodeficiência grave, uso de antibióticos ativos contra Salmonella",
        "efeitos_colaterais_comuns": "Dor local, febre baixa, cefaleia (injetável); náusea, dor abdominal, febre (oral)",
        "restricoes_para_gestantes": "Dados limitados; injetável preferível à oral na gestação; consultar médico",
        "eficacia_numerica": 70,
        "eficacia_descritiva": "55-72% de eficácia (injetável); 67-80% (oral); não substitui cuidados com água e alimentos",
        "duracao_da_protecao": "2-3 anos (injetável); 5 anos (oral)",
        "palavras_chave_ia": "febre tifoide vacina, viagem Asia Africa vacina tifoide, Typhim Vi, viajante vacina tifo",
        "perguntas_gatilho_ia": "Preciso de vacina para viajar para Índia? Vacina de febre tifóide onde tomar? Viagem para África precisa de qual vacina?",
        "resposta_padrao_sugerida": "A vacina para febre tifóide é indicada para viajantes para Ásia, África e partes da América Latina. São disponíveis na versão injetável (1 dose) ou oral (3 cápsulas). Não está na rotina do SUS, mas está disponível em clínicas de viagem e no CRIE para casos específicos.",
        "status_de_revisao": "Revisado",
    },
    {
        "id": "VAC031",
        "nome_da_vacina": "Cólera (Dukoral)",
        "nome_popular_apelido": "Vacina cólera, Dukoral, vacina oral cólera",
        "sinonimos_variacoes": "Dukoral, WC-rBS, cólera oral, vacina cólera oral, imunização cólera",
        "doencas_prevenidas": "Cólera (Vibrio cholerae O1) e diarreia por ETEC (parcialmente)",
        "tipo_de_vacina": "Bactéria inativada oral + subunidade B recombinante",
        "publico_alvo": "Viajantes para áreas de risco (Haiti, partes da África, Ásia Sul); trabalhadores humanitários; situações de surto",
        "faixa_etaria_recomendada": "A partir de 2 anos",
        "doses_totais_padrao": "2 doses (adultos e crianças ≥ 6 anos); 3 doses (crianças 2-6 anos)",
        "esquema_resumido": "Adultos: 2 doses com intervalo de 1 a 6 semanas | Crianças 2-6 anos: 3 doses com mesmo intervalo | Completar pelo menos 1 semana antes da viagem",
        "intervalo_entre_doses": "1 a 6 semanas entre doses; reforço a cada 2 anos (adultos) ou 6 meses (crianças 2-6 anos)",
        "via_de_administracao": "Oral (solução + efervescente)",
        "disponivel_no_sus": "Sim, via CRIE em situações especiais ou surtos",
        "disponivel_na_rede_privada": "Sim (com disponibilidade limitada)",
        "contraindicacoes": "Hipersensibilidade a componentes; não usar com antibióticos (esperar 3 dias)",
        "efeitos_colaterais_comuns": "Dor abdominal, náusea, diarreia, cefaleia (geralmente leves)",
        "restricoes_para_gestantes": "Evitar por precaução; não há dados suficientes",
        "eficacia_numerica": 85,
        "eficacia_descritiva": "85% de eficácia nas primeiras 6 semanas; 62% no 1º ano; não elimina necessidade de cuidados com água e alimentos",
        "palavras_chave_ia": "cólera vacina, Dukoral, viagem Haiti, vacina viagem cólera, diarreia viajante vacina",
        "perguntas_gatilho_ia": "Preciso de vacina de cólera para viajar? Existe vacina de cólera no Brasil? Dukoral onde comprar?",
        "resposta_padrao_sugerida": "A vacina oral contra cólera (Dukoral) é indicada para viajantes em risco. São 2 doses para adultos com 1-6 semanas de intervalo. Não é rotina no SUS, mas está disponível em clínicas de viagem e no CRIE para situações especiais.",
        "status_de_revisao": "Revisado",
    },
    {
        "id": "VAC032",
        "nome_da_vacina": "Encefalite Japonesa (Ixiaro)",
        "nome_popular_apelido": "Vacina encefalite japonesa, Ixiaro, EJ vacina",
        "sinonimos_variacoes": "Ixiaro, encefalite japonesa vacina, JE vaccine, Japanese encephalitis",
        "doencas_prevenidas": "Encefalite japonesa (arbovírus transmitido por mosquito Culex em áreas rurais da Ásia)",
        "tipo_de_vacina": "Vírus inativado",
        "publico_alvo": "Viajantes para áreas rurais da Ásia (China, Japão, Coreia, Índia, Sudeste Asiático) por ≥ 1 mês em período de transmissão; curto prazo em atividades de alto risco",
        "faixa_etaria_recomendada": "A partir de 2 meses (Ixiaro)",
        "doses_totais_padrao": "2 doses",
        "esquema_resumido": "2 doses com intervalo de 28 dias; última dose ≥ 1 semana antes da viagem",
        "intervalo_entre_doses": "28 dias",
        "via_de_administracao": "Intramuscular (IM)",
        "disponivel_no_sus": "Sim, via CRIE para indicações específicas",
        "disponivel_na_rede_privada": "Sim",
        "contraindicacoes": "Hipersensibilidade a componentes; gestação (evitar, salvo alto risco)",
        "efeitos_colaterais_comuns": "Dor local, cefaleia, mialgia, fadiga",
        "eficacia_numerica": 96,
        "eficacia_descritiva": ">96% de soroconversão após 2 doses",
        "duracao_da_protecao": "Reforço recomendado após 1-2 anos para viajantes com risco contínuo",
        "palavras_chave_ia": "encefalite japonesa vacina, Ixiaro, viagem Ásia vacina, mosquito encefalite Ásia, rural Ásia vacina",
        "perguntas_gatilho_ia": "Preciso de vacina para viajar ao Japão/China/Índia? Vacina de encefalite japonesa onde tomar? Viagem ao Sudeste Asiático precisa de qual vacina?",
        "resposta_padrao_sugerida": "A vacina contra encefalite japonesa (Ixiaro) é indicada para quem vai a áreas rurais da Ásia por mais de 1 mês. São 2 doses com 28 dias de intervalo. Está disponível no CRIE e em clínicas de viagem.",
        "status_de_revisao": "Revisado",
    },
    {
        "id": "VAC033",
        "nome_da_vacina": "Hepatite A + B combinada (Twinrix)",
        "nome_popular_apelido": "Twinrix, hepatite A e B combinada, hep A+B",
        "sinonimos_variacoes": "Twinrix, hepatite AB combinada, vacina dupla hepatite A hepatite B",
        "doencas_prevenidas": "Hepatite A e Hepatite B",
        "tipo_de_vacina": "Combinação: antígeno viral inativado (Hep A) + antígeno recombinante (Hep B)",
        "publico_alvo": "Adultos ≥ 18 anos sem imunidade comprovada para hepatite A e B",
        "faixa_etaria_recomendada": "A partir de 18 anos",
        "doses_totais_padrao": "3 doses (esquema padrão) ou 4 doses (esquema acelerado)",
        "esquema_resumido": "Padrão: 0, 1 e 6 meses | Acelerado: 0, 7, 21-30 dias + reforço aos 12 meses",
        "intervalo_entre_doses": "1 mês entre 1ª e 2ª; 5 meses entre 2ª e 3ª (esquema padrão)",
        "via_de_administracao": "Intramuscular (IM)",
        "local_de_aplicacao_no_corpo": "Deltóide",
        "disponivel_no_sus": "Não (o SUS oferece Hep A e Hep B separadamente — ver VAC005 e VAC014)",
        "disponivel_na_rede_privada": "Sim",
        "onde_se_vacinar": "Clínicas de vacinação particulares",
        "contraindicacoes": "Hipersensibilidade a componentes de qualquer uma das vacinas",
        "efeitos_colaterais_comuns": "Dor local, cefaleia, fadiga, náusea",
        "restricoes_para_gestantes": "Usar somente se claramente indicado — avaliar com médico",
        "eficacia_descritiva": "Eficácia equivalente às vacinas separadas: ~95% para Hep A e 95% para Hep B após série completa",
        "duracao_da_protecao": "Hepatite A: décadas (possivelmente vitalícia); Hepatite B: ≥ 20 anos",
        "palavras_chave_ia": "Twinrix, hepatite A B combinada, vacina dupla hepatite, hep AB adulto particular",
        "perguntas_gatilho_ia": "Posso tomar hepatite A e B juntas? Existe vacina combinada de hepatite? Twinrix tem no SUS?",
        "resposta_padrao_sugerida": "Sim, existe a Twinrix que combina hepatite A e B em 1 injeção — 3 doses ao longo de 6 meses. Não está no SUS (o SUS oferece as duas separadamente). Para adultos que precisam das duas hepatites, a Twinrix pode ser mais prática.",
        "status_de_revisao": "Revisado",
    },
    {
        "id": "VAC034",
        "nome_da_vacina": "Pneumocócica 15-valente (PCV15 / Vaxneuvance)",
        "nome_popular_apelido": "Vaxneuvance, pneumo 15, PCV15",
        "sinonimos_variacoes": "PCV15, Vaxneuvance, pneumocócica 15 valente, pneumo conjugada 15",
        "doencas_prevenidas": "Pneumonia, meningite e sepse por 15 sorotipos de Streptococcus pneumoniae",
        "tipo_de_vacina": "Polissacarídeo conjugado",
        "publico_alvo": "Adultos ≥ 65 anos; adultos de 19-64 anos com comorbidades; crianças (em uso fora de bula ou conforme indicação específica)",
        "faixa_etaria_recomendada": "Adultos ≥ 19 anos",
        "doses_totais_padrao": "1 dose (adultos não vacinados); pode ser seguida de PPV23 após ≥ 1 ano",
        "esquema_resumido": "Adultos não vacinados: 1 dose PCV15; após ≥ 1 ano, considerar PPV23. Substitui PCV13 em adultos.",
        "via_de_administracao": "Intramuscular (IM)",
        "local_de_aplicacao_no_corpo": "Deltóide",
        "disponivel_no_sus": "Não (disponível apenas na rede privada)",
        "disponivel_na_rede_privada": "Sim",
        "contraindicacoes": "Hipersensibilidade a componentes",
        "efeitos_colaterais_comuns": "Dor local, vermelhidão, inchaço; cefaleia; fadiga",
        "restricoes_para_gestantes": "Dados limitados — avaliar com médico",
        "eficacia_descritiva": "Imunogenicidade superior à PCV13 para os 2 sorotipos adicionais (22F e 33F); comparável para os 13 sorotipos em comum",
        "palavras_chave_ia": "PCV15, Vaxneuvance, pneumococo 15, vacina pneumonia adulto particular, pneumo mais completa adulto",
        "perguntas_gatilho_ia": "Qual a vacina de pneumonia mais nova? PCV15 é melhor que PCV13? Qual vacina de pneumococo para adultos?",
        "resposta_padrao_sugerida": "A PCV15 (Vaxneuvance) é uma vacina mais recente contra pneumococo, cobrindo 15 sorotipos. É indicada para adultos, especialmente ≥ 65 anos e pessoas com comorbidades. Disponível apenas em clínicas particulares. O SUS oferece a PCV10 para crianças e PPV23 para grupos específicos.",
        "status_de_revisao": "Revisado",
    },
]


def main():
    print(f"\n🌿 VacinaFácil AI — Adicionando {len(VACINAS_NOVAS)} vacinas\n")

    # IDs já existentes
    res = supabase.table("vacinas").select("id").execute()
    existentes = {r["id"] for r in res.data}
    print(f"   Vacinas já no banco: {len(existentes)}")

    inseridas = 0
    ignoradas = 0

    for v in VACINAS_NOVAS:
        if v["id"] in existentes:
            print(f"   ⏭  {v['id']} já existe — pulando")
            ignoradas += 1
            continue
        try:
            supabase.table("vacinas").insert(v).execute()
            print(f"   ✅ {v['id']}: {v['nome_da_vacina']}")
            inseridas += 1
        except Exception as e:
            print(f"   ❌ {v['id']}: ERRO — {e}")

    print(f"\n{'='*50}")
    print(f"✅ Inseridas: {inseridas} | Ignoradas: {ignoradas}")
    print(f"   Total no banco: {len(existentes) + inseridas} vacinas")
    print("="*50)
    print("\nPróximo passo: rodar python gerar_embeddings.py para indexar as novas vacinas")


if __name__ == "__main__":
    main()
