"""
VacinaFácil AI — Enriquece os 21 campos faltantes das 12 vacinas novas
Uso: python enriquecer_vacinas.py
"""

import os
from dotenv import load_dotenv
from supabase import create_client

load_dotenv(override=True)
supabase = create_client(os.getenv("SUPABASE_URL"), os.getenv("SUPABASE_SERVICE_KEY"))

ATUALIZACOES = {
    "VAC023": {  # VOP
        "fabricante_laboratorio": "Bio-Manguinhos/Fiocruz (Brasil); GSK; Sanofi",
        "composicao_principal": "Vírus atenuado vivo dos poliovírus tipos 1 e 3 (bOPV — bivalente oral)",
        "tipo_de_esquema": "Reforço — complementa o esquema primário de VIP injetável",
        "reforcos": "2 reforços orais: 15 meses e 4 anos",
        "substitui_e_substituida_por": "Substituiu parcialmente a OPV trivalente (que incluía tipo 2); o tipo 2 foi erradicado. Doses primárias são VIP (VAC007).",
        "documentos_necessarios": "Caderneta de vacinação; CPF ou CNS",
        "precisa_de_receita_medica": "Não",
        "calendario_pni": "Calendário da Criança — 1º reforço: 15 meses | 2º reforço: 4 anos",
        "o_que_fazer_em_caso_de_reacao": "A vacina oral raramente causa reações. Em caso de febre alta (>39°C) ou qualquer sinal neurológico (fraqueza de membro, dificuldade de movimento), procure UBS imediatamente.",
        "quando_procurar_atendimento_urgente": "Fraqueza súbita em membros após vacinação; febre muito alta persistente; alteração de comportamento",
        "pode_tomar_junto_com_outras_vacinas": "Sim — pode ser administrada junto com outras vacinas do calendário infantil no mesmo dia",
        "restricoes_para_lactantes": "Pode ser administrada em lactantes — não há restrição",
        "restricoes_para_alergicos": "Contraindicada em alérgicos graves a componentes da vacina (neomicina, estreptomicina)",
        "registro_no_cartao_de_vacinacao": "Registrar como 'VOP' + data + lote na caderneta de vacinação",
        "pergunta_de_followup_sugerida": "Seu filho já tomou as doses injetáveis da VIP aos 2, 4 e 6 meses? O esquema completo usa as duas vacinas juntas.",
        "quando_encaminhar_a_profissional": "Criança imunodeprimida — encaminhar para CRIE para usar VIP ao invés de VOP; contato domiciliar imunodeprimido",
        "nivel_de_confianca_da_info": "Alto — fonte: PNI/MS 2024",
        "fonte_oficial_id": "FONTE001",
        "ultima_atualizacao": "2024-01-01",
        "responsavel_pela_curadoria": "VacinaFácil AI — dados PNI/MS",
        "observacoes_internas": "Brasil usa esquema sequencial VIP (2,4,6m) + VOP (15m, 4a) desde 2012",
    },
    "VAC024": {  # PCV13
        "fabricante_laboratorio": "Pfizer (Prevnar 13)",
        "composicao_principal": "Polissacarídeos capsulares de 13 sorotipos de S. pneumoniae (1, 3, 4, 5, 6A, 6B, 7F, 9V, 14, 18C, 19A, 19F, 23F) conjugados à proteína carreadora CRM197",
        "tipo_de_esquema": "Primário + reforço (crianças) ou dose única/dupla (adultos de risco)",
        "reforcos": "Crianças: reforço aos 12-15 meses | Adultos imunodeprimidos: sequenciar com PPV23 após ≥ 8 semanas",
        "substitui_e_substituida_por": "É complementada pela PPV23 (VAC019) em adultos de risco; PCV15 é versão mais nova para adultos",
        "documentos_necessarios": "Laudo médico comprovando condição de risco para acesso via CRIE; CPF/CNS",
        "precisa_de_receita_medica": "Sim — para acesso via CRIE (necessita laudo); na rede privada, não obrigatoriamente",
        "calendario_pni": "Não é do calendário de rotina — disponível via CRIE para grupos especiais (HIV+, imunodeprimidos, asplênicos, transplantados)",
        "o_que_fazer_em_caso_de_reacao": "Dor, vermelhidão ou inchaço local: compressa fria e analgésico se necessário. Febre: antitérmico conforme orientação médica. Reação alérgica grave (urticária, falta de ar): SAMU 192.",
        "quando_procurar_atendimento_urgente": "Dificuldade respiratória, urticária generalizada ou edema de face após vacinação — sinais de anafilaxia",
        "pode_tomar_junto_com_outras_vacinas": "Sim, pode ser administrada com outras vacinas; usar locais diferentes de aplicação",
        "restricoes_para_lactantes": "Pode ser administrada durante amamentação — sem restrições",
        "restricoes_para_alergicos": "Contraindicada em hipersensibilidade grave ao toxoide diftérico (CRM197) ou a qualquer componente",
        "registro_no_cartao_de_vacinacao": "Registrar como 'PCV13' + data + lote; anotar se é série primária ou reforço",
        "pergunta_de_followup_sugerida": "Você tem HIV, usa imunossupressor ou fez transplante? Nesses casos há indicação especial de sequência PCV13 + PPV23.",
        "quando_encaminhar_a_profissional": "Sempre — indicação é médica; encaminhar ao CRIE com laudo da condição de risco",
        "nivel_de_confianca_da_info": "Alto — fonte: CRIE/MS, ACIP 2023",
        "fonte_oficial_id": "FONTE001",
        "ultima_atualizacao": "2024-01-01",
        "responsavel_pela_curadoria": "VacinaFácil AI — dados PNI/MS",
        "observacoes_internas": "PCV13 foi substituída pela PCV15 nas recomendações ACIP 2021 para adultos, mas ainda amplamente usada no Brasil via CRIE",
    },
    "VAC025": {  # Shingrix
        "fabricante_laboratorio": "GSK (GlaxoSmithKline) — Shingrix",
        "composicao_principal": "Glicoproteína E (gE) do vírus varicela-zóster + adjuvante AS01B (MPL + QS-21)",
        "tipo_de_esquema": "Série primária de 2 doses — sem reforço definido até o momento",
        "reforcos": "Não há reforço recomendado até o momento; estudos de longa duração em andamento",
        "substitui_e_substituida_por": "Substitui a vacina Zostavax (atenuada, 1 dose) que era usada anteriormente — Shingrix é mais eficaz e segura para imunodeprimidos",
        "documentos_necessarios": "Não precisa de receita médica para compra; recomendável consultar médico antes",
        "precisa_de_receita_medica": "Não obrigatoriamente, mas recomendado consultar médico",
        "calendario_pni": "Não faz parte do calendário PNI — vacina da rede privada",
        "o_que_fazer_em_caso_de_reacao": "Dor intensa no local, febre, calafrios e fadiga são esperados (efeito do adjuvante AS01B) — geralmente passam em 1-3 dias. Use analgésico/antitérmico se necessário. Procure médico se sintomas persistirem > 3 dias ou forem muito intensos.",
        "quando_procurar_atendimento_urgente": "Dificuldade respiratória, urticária, inchaço de face ou lábios logo após a vacina (anafilaxia — SAMU 192); dor no peito ou sintomas neurológicos incomuns",
        "pode_tomar_junto_com_outras_vacinas": "Sim — pode ser administrada com Influenza e outras vacinas. Usar locais separados.",
        "restricoes_para_lactantes": "Dados limitados; por precaução, discutir com médico — provavelmente segura durante amamentação",
        "restricoes_para_alergicos": "Contraindicada em hipersensibilidade a qualquer componente da vacina; verificar alergia a polissorbato 80",
        "registro_no_cartao_de_vacinacao": "Registrar 'Shingrix dose 1' e 'Shingrix dose 2' com datas e lotes; guardar comprovante da clínica",
        "pergunta_de_followup_sugerida": "Você já teve cobreiro antes? Mesmo quem já teve pode e deve vacinar para evitar nova recorrência.",
        "quando_encaminhar_a_profissional": "Imunodeprimidos graves em tratamento ativo — discutir momento ideal com oncologista/infectologista antes de vacinar",
        "nivel_de_confianca_da_info": "Alto — fonte: bula Shingrix, SBIm 2024, ACIP 2022",
        "fonte_oficial_id": "FONTE002",
        "ultima_atualizacao": "2024-01-01",
        "responsavel_pela_curadoria": "VacinaFácil AI — dados SBIm/bula",
        "observacoes_internas": "Efeitos colaterais são frequentes e intensos por causa do adjuvante AS01B — paciente deve ser avisado para não interpretar como reação grave",
    },
    "VAC026": {  # MenB
        "fabricante_laboratorio": "GSK (Bexsero) — principal marca disponível no Brasil",
        "composicao_principal": "4 componentes proteicos recombinantes: fHbp, NHBA, NadA e OMVNZ (vesículas de membrana externa de cepa NZ98/254)",
        "tipo_de_esquema": "Série primária variável por faixa etária + reforço",
        "reforcos": "Crianças < 6 meses: reforço aos 12-15 meses | Crianças 6-11 meses: reforço após 1º ano | Adultos: sem reforço de rotina",
        "substitui_e_substituida_por": "Complementa a MenC (VAC010) e MenACWY (VAC018) — cobre o sorogrupo B que as outras não cobrem",
        "documentos_necessarios": "Não exige receita na maioria das clínicas",
        "precisa_de_receita_medica": "Não obrigatoriamente",
        "calendario_pni": "Não faz parte do calendário PNI universal — vacina da rede privada; SBIm recomenda no calendário privado",
        "o_que_fazer_em_caso_de_reacao": "Febre, irritabilidade e dor local são comuns, especialmente em lactentes. Use antitérmico conforme peso. Compressa fria no local. Em caso de febre muito alta (>40°C) ou convulsão: SAMU 192.",
        "quando_procurar_atendimento_urgente": "Febre acima de 40°C; convulsão; choro inconsolável por mais de 3 horas; dificuldade respiratória; reação alérgica (urticária, inchaço de face)",
        "pode_tomar_junto_com_outras_vacinas": "Pode ser administrada junto com outras vacinas, mas em locais separados. Atenção: risco maior de febre quando combinada com outras vacinas em lactentes.",
        "restricoes_para_lactantes": "Pode ser administrada durante amamentação — sem restrições",
        "restricoes_para_alergicos": "Contraindicada em alergia grave a qualquer componente",
        "registro_no_cartao_de_vacinacao": "Registrar 'MenB / Bexsero' + número da dose + data + lote",
        "pergunta_de_followup_sugerida": "Seu filho também tomou a vacina de meningite C (MenC) e MenACWY? A proteção completa contra meningite meningocócica requer todas as vacinas cobertas.",
        "quando_encaminhar_a_profissional": "Crianças asplênicas, com deficiência de complemento ou HIV — encaminhar para CRIE/imunologista para esquema personalizado",
        "nivel_de_confianca_da_info": "Alto — fonte: bula Bexsero, SBIm 2024",
        "fonte_oficial_id": "FONTE002",
        "ultima_atualizacao": "2024-01-01",
        "responsavel_pela_curadoria": "VacinaFácil AI — dados SBIm/bula",
        "observacoes_internas": "Bexsero é a única MenB disponível comercialmente no Brasil. Trumenba (Pfizer) não está registrada no Brasil.",
    },
    "VAC027": {  # Gardasil 9
        "fabricante_laboratorio": "Merck Sharp & Dohme (MSD) — Gardasil 9",
        "composicao_principal": "Partículas semelhantes a vírus (VLP) purificadas de 9 tipos de HPV (6, 11, 16, 18, 31, 33, 45, 52, 58) expressas em Saccharomyces cerevisiae",
        "tipo_de_esquema": "2 doses (9-14 anos) ou 3 doses (≥ 15 anos e imunodeprimidos)",
        "reforcos": "Não há reforço recomendado após série completa",
        "substitui_e_substituida_por": "É a versão mais completa; substitui a Gardasil 4-valente (que cobria apenas 6, 11, 16, 18). O SUS usa a quadrivalente (VAC002).",
        "documentos_necessarios": "Não exige receita médica; menores de 18 anos precisam de acompanhante ou autorização dos pais",
        "precisa_de_receita_medica": "Não",
        "calendario_pni": "Gardasil 9 não faz parte do PNI — o SUS oferece a HPV quadrivalente (VAC002) para 9-14 anos (meninas) e 11-14 anos (meninos)",
        "o_que_fazer_em_caso_de_reacao": "Dor, vermelhidão e inchaço locais: compressa fria e analgésico se necessário. Tontura ou desmaio (vasovagal — comum em adolescentes): deitar por 15 minutos após a vacina. Reação alérgica grave: SAMU 192.",
        "quando_procurar_atendimento_urgente": "Dificuldade respiratória, urticária generalizada, inchaço de face/língua/garganta logo após vacina — anafilaxia",
        "pode_tomar_junto_com_outras_vacinas": "Pode ser administrada com MenACWY e outras vacinas; usar locais diferentes",
        "restricoes_para_lactantes": "Pode ser administrada durante amamentação — sem restrições",
        "restricoes_para_alergicos": "Contraindicada em alergia grave a levedura (Saccharomyces cerevisiae) ou componentes",
        "registro_no_cartao_de_vacinacao": "Registrar 'HPV 9 (Gardasil 9)' + número da dose + data + lote",
        "pergunta_de_followup_sugerida": "Você já iniciou o esquema de HPV pelo SUS? Se começou com a quadrivalente, pode completar com Gardasil 9 — consulte seu médico.",
        "quando_encaminhar_a_profissional": "HIV positivos e imunodeprimidos: 3 doses independentemente da idade; orientar a consultar médico para confirmar indicação",
        "nivel_de_confianca_da_info": "Alto — fonte: bula Gardasil 9, SBIm 2024, ACIP 2023",
        "fonte_oficial_id": "FONTE002",
        "ultima_atualizacao": "2024-01-01",
        "responsavel_pela_curadoria": "VacinaFácil AI — dados SBIm/bula",
        "observacoes_internas": "Recomendável deitar o adolescente por 15 min após a vacina para evitar vasovagal/síncope — comum nessa faixa etária",
    },
    "VAC028": {  # Mpox
        "fabricante_laboratorio": "Bavarian Nordic (Jynneos / Imvamune / Imvanex)",
        "composicao_principal": "Vírus Vaccinia Modificado Ankara (MVA-BN) — vírus vivo não replicativo",
        "tipo_de_esquema": "2 doses com 28 dias de intervalo (pré-exposição) | 1 dose em até 4 dias pós-exposição",
        "reforcos": "Reforço a cada 2 anos em pessoas com risco contínuo — verificar protocolo CRIE atualizado",
        "substitui_e_substituida_por": "Substitui a vacina da varíola humana (ACAM2000) que era replicativa e contraindicada para imunodeprimidos",
        "documentos_necessarios": "Encaminhamento médico ou autodeclaração de pertencer a grupo de risco para CRIE; CPF/CNS",
        "precisa_de_receita_medica": "Sim — acesso via CRIE mediante avaliação de risco",
        "calendario_pni": "Não é rotina universal — disponível via CRIE para grupos de risco específicos",
        "o_que_fazer_em_caso_de_reacao": "Dor, vermelhidão e inchaço local: compressa fria. Fadiga, cefaleia, mialgia: analgésico conforme necessidade. Febre alta ou reação no local que se espalhe: procurar atendimento médico.",
        "quando_procurar_atendimento_urgente": "Dificuldade respiratória, urticária generalizada, inchaço de face — anafilaxia (SAMU 192); lesões de pele que surgem após vacinação (raro com MVA)",
        "pode_tomar_junto_com_outras_vacinas": "Dados limitados; por precaução, administrar em locais separados; consultar médico para coadministração",
        "restricoes_para_lactantes": "Dados muito limitados; avaliar risco/benefício com médico",
        "restricoes_para_alergicos": "Contraindicada em hipersensibilidade grave a componentes; verificar alergia a gentamicina, ciprofloxacino e outros excipientes",
        "registro_no_cartao_de_vacinacao": "Registrar 'Mpox/Jynneos dose 1' e 'dose 2' + data + lote; guardar comprovante do CRIE",
        "pergunta_de_followup_sugerida": "Você tem parceiros sexuais múltiplos ou frequenta ambientes de alto risco? A vacinação é mais eficaz quando feita antes da exposição.",
        "quando_encaminhar_a_profissional": "Sempre — a indicação é definida pelo CRIE ou infectologista conforme critérios de risco",
        "nivel_de_confianca_da_info": "Alto — fonte: MS/SVS Nota Técnica Mpox 2022-2024",
        "fonte_oficial_id": "FONTE001",
        "ultima_atualizacao": "2024-01-01",
        "responsavel_pela_curadoria": "VacinaFácil AI — dados MS/SVS",
        "observacoes_internas": "Via intradérmica (0,1 mL) pode ser usada para expandir o número de doses disponíveis durante surtos; via SC (0,5 mL) é a padrão",
    },
    "VAC029": {  # Nirsevimabe
        "fabricante_laboratorio": "Sanofi / AstraZeneca — Beyfortus (nirsevimabe)",
        "composicao_principal": "Anticorpo monoclonal IgG1κ humanizado contra a proteína F do VSR (pré-fusão estabilizada); meia-vida prolongada por modificação YTE",
        "tipo_de_esquema": "Dose única sazonal (antes ou no início da temporada de VSR — outono/inverno)",
        "reforcos": "Dose anual recomendada — uma dose por temporada de VSR nos primeiros 2 anos de vida em grupos de risco",
        "substitui_e_substituida_por": "Substitui o palivizumabe (Synagis) em muitos contextos — nirsevimabe tem meia-vida maior e cobre mais cepas",
        "documentos_necessarios": "Receita médica na rede privada; via SUS (quando incorporado): caderneta de vacinação e CNS",
        "precisa_de_receita_medica": "Sim — receita médica na rede privada",
        "calendario_pni": "Em processo de incorporação ao PNI (avaliação CONITEC 2024) — verificar atualização mais recente",
        "o_que_fazer_em_caso_de_reacao": "Dor, vermelhidão local: compressa fria. Febre: antitérmico conforme peso. Se o bebê apresentar dificuldade respiratória, recusa alimentar intensa ou palidez: SAMU 192.",
        "quando_procurar_atendimento_urgente": "Dificuldade respiratória, palidez intensa, cianose (boca/unhas azuladas), recusa alimentar total — podem indicar infecção respiratória grave mesmo após o anticorpo",
        "pode_tomar_junto_com_outras_vacinas": "Sim — pode ser administrado junto com outras vacinas do calendário infantil no mesmo dia",
        "restricoes_para_lactantes": "Não se aplica — é administrado no bebê, não na mãe que amamenta",
        "restricoes_para_alergicos": "Contraindicado em hipersensibilidade conhecida ao nirsevimabe",
        "registro_no_cartao_de_vacinacao": "Registrar 'Nirsevimabe (Beyfortus)' + data + lote na caderneta do bebê",
        "pergunta_de_followup_sugerida": "Seu bebê nasceu prematuro ou tem doença cardíaca/pulmonar? Nesses casos o nirsevimabe é especialmente indicado.",
        "quando_encaminhar_a_profissional": "Bebês com cardiopatia congênita, displasia broncopulmonar ou imunocomprometidos — encaminhar a pediatra especialista para indicação formal",
        "nivel_de_confianca_da_info": "Alto — fonte: bula Beyfortus, AAP 2023, CONITEC 2024",
        "fonte_oficial_id": "FONTE001",
        "ultima_atualizacao": "2024-01-01",
        "responsavel_pela_curadoria": "VacinaFácil AI — dados CONITEC/AAP",
        "observacoes_internas": "Não é tecnicamente uma vacina (não induz resposta imune ativa), mas funciona como imunoprofilaxia passiva. Importante esclarecer isso para famílias.",
    },
    "VAC030": {  # Febre Tifóide
        "fabricante_laboratorio": "Sanofi Pasteur (Typhim Vi); GSK (Typherix)",
        "composicao_principal": "Polissacarídeo capsular Vi purificado de Salmonella enterica Typhi",
        "tipo_de_esquema": "Dose única (Vi-CPS injetável) | 3 cápsulas em dias alternados (Vivotif oral — disponibilidade limitada no Brasil)",
        "reforcos": "A cada 3 anos para exposição contínua (injetável); a cada 5 anos (oral)",
        "substitui_e_substituida_por": "Vivotif oral é alternativa à injetável; vacinas mais antigas de célula inteira foram substituídas pela Vi-CPS por melhor tolerabilidade",
        "documentos_necessarios": "Não exige receita na maioria das clínicas de viagem; para CRIE: laudo ou comprovação de risco",
        "precisa_de_receita_medica": "Não obrigatoriamente",
        "calendario_pni": "Não faz parte do calendário de rotina; disponível via CRIE para situações especiais (surtos, trabalhadores de saneamento)",
        "o_que_fazer_em_caso_de_reacao": "Dor, vermelhidão local: compressa fria. Febre baixa e cefaleia: analgésico/antitérmico. Sintomas gastrointestinais (oral): geralmente autolimitados.",
        "quando_procurar_atendimento_urgente": "Febre alta persistente; vômitos repetidos; urticária ou dificuldade respiratória (anafilaxia — SAMU 192)",
        "pode_tomar_junto_com_outras_vacinas": "Sim — pode ser administrada com outras vacinas de viagem (febre amarela, hepatite A/B, etc.)",
        "restricoes_para_lactantes": "Injetável: provavelmente segura; oral: evitar por precaução — preferir a injetável",
        "restricoes_para_alergicos": "Contraindicada em hipersensibilidade a componentes; oral: não usar com antibióticos ativos contra Salmonella",
        "registro_no_cartao_de_vacinacao": "Registrar na carteira de vacinação de viagem ou caderneta; anotar data para controle do reforço trienal",
        "pergunta_de_followup_sugerida": "Você vai também para áreas com risco de hepatite A? As duas vacinas podem ser tomadas na mesma visita.",
        "quando_encaminhar_a_profissional": "Imunocomprometidos: usar injetável (não oral atenuada); gestantes: avaliar com obstetra",
        "nivel_de_confianca_da_info": "Alto — fonte: OMS/SAGE, SBIm Guia de Viagem 2024",
        "fonte_oficial_id": "FONTE003",
        "ultima_atualizacao": "2024-01-01",
        "responsavel_pela_curadoria": "VacinaFácil AI — dados SBIm/OMS",
        "observacoes_internas": "A vacina NÃO substitui cuidados com água e alimentos em áreas endêmicas — informar viajantes sobre higiene alimentar",
    },
    "VAC031": {  # Cólera
        "fabricante_laboratorio": "Valneva (Dukoral) — licenciado no Brasil",
        "composicao_principal": "Vibrio cholerae O1 inativado (Inaba e Ogawa, clássico e El Tor) + subunidade B recombinante da toxina colérica (rCTB)",
        "tipo_de_esquema": "Adultos: 2 doses com 1-6 semanas de intervalo; crianças 2-6 anos: 3 doses",
        "reforcos": "Adultos: a cada 2 anos em risco contínuo; crianças 2-6 anos: a cada 6 meses",
        "substitui_e_substituida_por": "Substitui vacinas de células inteiras injetáveis (não mais usadas). Dukoral também confere proteção parcial (~67%) contra diarreia por ETEC.",
        "documentos_necessarios": "Não exige receita em clínicas de viagem",
        "precisa_de_receita_medica": "Não obrigatoriamente",
        "calendario_pni": "Não é de rotina; disponível via CRIE para surtos e situações especiais",
        "o_que_fazer_em_caso_de_reacao": "Dor abdominal leve, náusea ou diarreia: sintomáticos e hidratação. Geralmente autolimitados em 24h.",
        "quando_procurar_atendimento_urgente": "Diarreia muito intensa com desidratação; vômitos persistentes; urticária (anafilaxia — rara)",
        "pode_tomar_junto_com_outras_vacinas": "Sim — não há interações conhecidas com outras vacinas de viagem",
        "restricoes_para_lactantes": "Evitar por precaução — dados insuficientes",
        "restricoes_para_alergicos": "Contraindicado em hipersensibilidade a componentes do Dukoral",
        "registro_no_cartao_de_vacinacao": "Registrar 'Dukoral dose 1/2' + datas + lote na carteira de vacinação de viagem",
        "pergunta_de_followup_sugerida": "Você também vai tomar a vacina de febre tifóide? As duas são importantes para viagens a áreas com saneamento precário.",
        "quando_encaminhar_a_profissional": "Imunocomprometidos, gestantes, crianças < 2 anos: avaliar com médico antes",
        "nivel_de_confianca_da_info": "Alto — fonte: OMS/SAGE, bula Dukoral",
        "fonte_oficial_id": "FONTE003",
        "ultima_atualizacao": "2024-01-01",
        "responsavel_pela_curadoria": "VacinaFácil AI — dados OMS/bula",
        "observacoes_internas": "Dukoral é diluído em solução tampão efervescente — não ingerir alimentos/medicamentos 1h antes e depois. Proteção parcial contra ETEC é bônus valioso para viajantes.",
    },
    "VAC032": {  # Encefalite Japonesa
        "fabricante_laboratorio": "Valneva (Ixiaro)",
        "composicao_principal": "Vírus da encefalite japonesa (cepa SA14-14-2) inativado, adsorvido em hidróxido de alumínio",
        "tipo_de_esquema": "2 doses com intervalo de 28 dias; concluir pelo menos 1 semana antes da chegada",
        "reforcos": "Reforço único 12-24 meses após a série primária para viajantes com risco contínuo",
        "substitui_e_substituida_por": "Substitui a vacina JE-VAX (camundongo inativado), retirada do mercado por efeitos adversos; Ixiaro tem melhor perfil de segurança",
        "documentos_necessarios": "Não exige receita; disponível em clínicas de viagem e CRIE",
        "precisa_de_receita_medica": "Não obrigatoriamente",
        "calendario_pni": "Não é de rotina; disponível via CRIE para indicações específicas",
        "o_que_fazer_em_caso_de_reacao": "Dor local, cefaleia, mialgia: analgésico/antitérmico. Febre: antitérmico. Reações tardias (urticária, angioedema) podem ocorrer até 10 dias — procurar médico.",
        "quando_procurar_atendimento_urgente": "Urticária, angioedema (inchaço), dificuldade respiratória em qualquer momento após a vacina (anafilaxia — SAMU 192)",
        "pode_tomar_junto_com_outras_vacinas": "Pode ser administrada com vacinas de viagem; dados limitados de coadministração — usar locais separados",
        "restricoes_para_lactantes": "Dados muito limitados; avaliar risco/benefício com médico",
        "restricoes_para_alergicos": "Contraindicada em hipersensibilidade grave a componentes; verificar alergia a protamina (sulfato de protamina é excipiente)",
        "registro_no_cartao_de_vacinacao": "Registrar 'Ixiaro dose 1/2' + data + lote; anotar para controle do reforço",
        "pergunta_de_followup_sugerida": "Quanto tempo você vai ficar na Ásia? Viagens curtas (< 1 semana) em áreas urbanas têm risco muito baixo; a vacina é mais indicada para estadias longas em áreas rurais.",
        "quando_encaminhar_a_profissional": "Gestantes, imunodeprimidos e crianças < 2 meses: avaliação médica antes da vacinação",
        "nivel_de_confianca_da_info": "Alto — fonte: OMS/SAGE, bula Ixiaro, CDC Yellow Book 2024",
        "fonte_oficial_id": "FONTE003",
        "ultima_atualizacao": "2024-01-01",
        "responsavel_pela_curadoria": "VacinaFácil AI — dados CDC/OMS",
        "observacoes_internas": "Encefalite japonesa tem mortalidade de 25-30% e 30-50% dos sobreviventes ficam com sequelas neurológicas permanentes — importante comunicar gravidade ao viajante",
    },
    "VAC033": {  # Twinrix
        "fabricante_laboratorio": "GSK (GlaxoSmithKline) — Twinrix Adulto",
        "composicao_principal": "720 unidades ELISA de antígeno Hep A inativado (HAV cepa HM175) + 20 mcg antígeno recombinante HBsAg; adjuvante Al(OH)3 + AlPO4",
        "tipo_de_esquema": "Padrão: 3 doses (0, 1 e 6 meses) | Acelerado: 4 doses (0, 7, 21 dias + reforço aos 12 meses)",
        "reforcos": "Não indicado de rotina após série completa; anticorpos Hep B podem requerer monitoramento em situações de risco",
        "substitui_e_substituida_por": "Substituição prática das vacinas separadas de Hep A (VAC014) e Hep B (VAC005) em adultos que precisam das duas",
        "documentos_necessarios": "Não exige receita",
        "precisa_de_receita_medica": "Não",
        "calendario_pni": "Não faz parte do PNI — o SUS oferece Hep A (crianças) e Hep B (rotina) separadamente e gratuitamente",
        "o_que_fazer_em_caso_de_reacao": "Dor, vermelhidão local: compressa fria. Cefaleia, fadiga: analgésico. Febre baixa: antitérmico. Reação alérgica grave (urticária, falta de ar): SAMU 192.",
        "quando_procurar_atendimento_urgente": "Dificuldade respiratória, urticária generalizada, edema de lábios/face após vacinação",
        "pode_tomar_junto_com_outras_vacinas": "Pode ser administrada com outras vacinas; usar locais separados",
        "restricoes_para_lactantes": "Provavelmente segura; discutir com médico se necessário",
        "restricoes_para_alergicos": "Contraindicada em hipersensibilidade a qualquer componente; verificar alergia a neomicina, formol e polissorbato 20",
        "registro_no_cartao_de_vacinacao": "Registrar 'Twinrix dose 1/2/3' + datas + lotes",
        "pergunta_de_followup_sugerida": "Você já tem anticorpos para Hep A ou Hep B por infecção prévia? Sorologia prévia pode definir se precisa de 1 ou 2 componentes.",
        "quando_encaminhar_a_profissional": "Hemodialisados e imunodeprimidos: monitoramento de anticorpos após série; esquemas especiais podem ser necessários",
        "nivel_de_confianca_da_info": "Alto — fonte: bula Twinrix, SBIm 2024",
        "fonte_oficial_id": "FONTE002",
        "ultima_atualizacao": "2024-01-01",
        "responsavel_pela_curadoria": "VacinaFácil AI — dados SBIm/bula",
        "observacoes_internas": "Para adultos sem vacinação anterior para ambas as hepatites, Twinrix é custo-efetivo pela conveniência de reduzir número de injeções",
    },
    "VAC034": {  # PCV15
        "fabricante_laboratorio": "MSD — Merck Sharp & Dohme (Vaxneuvance)",
        "composicao_principal": "Polissacarídeos capsulares de 15 sorotipos de S. pneumoniae (1, 3, 4, 5, 6A, 6B, 7F, 9V, 14, 18C, 19A, 19F, 22F, 23F, 33F) conjugados à proteína carreadora CRM197",
        "tipo_de_esquema": "Adultos: dose única; pode ser seguida de PPV23 após ≥ 1 ano",
        "reforcos": "PPV23 (VAC019) após ≥ 1 ano para maximizar cobertura de sorotipos em adultos de risco",
        "substitui_e_substituida_por": "Substitui PCV13 em adultos — adiciona sorotipos 22F e 33F. PCV20 (Prevnar 20) também disponível e cobre ainda mais sorotipos.",
        "documentos_necessarios": "Não exige receita",
        "precisa_de_receita_medica": "Não obrigatoriamente; recomendado consultar médico",
        "calendario_pni": "Não faz parte do calendário PNI de rotina para adultos — rede privada; SUS oferece PCV10 para crianças e PPV23 via CRIE",
        "o_que_fazer_em_caso_de_reacao": "Dor, vermelhidão, inchaço local: compressa fria. Cefaleia, fadiga: analgésico. Febre baixa: antitérmico. Anafilaxia: SAMU 192.",
        "quando_procurar_atendimento_urgente": "Dificuldade respiratória, urticária, edema de face após vacinação",
        "pode_tomar_junto_com_outras_vacinas": "Pode ser administrada com Influenza e outras vacinas; usar locais separados",
        "restricoes_para_lactantes": "Dados limitados; provavelmente segura — discutir com médico",
        "restricoes_para_alergicos": "Contraindicada em hipersensibilidade ao toxoide diftérico (CRM197) ou componentes",
        "registro_no_cartao_de_vacinacao": "Registrar 'PCV15/Vaxneuvance' + data + lote; anotar PPV23 subsequente se indicado",
        "pergunta_de_followup_sugerida": "Você tem mais de 65 anos ou alguma doença crônica (diabetes, DPOC, insuficiência cardíaca)? Nesses casos a vacina é especialmente benéfica.",
        "quando_encaminhar_a_profissional": "Imunodeprimidos graves: avaliar sequência PCV15 + PPV23 com médico; verificar interações com outros imunobiológicos",
        "nivel_de_confianca_da_info": "Alto — fonte: bula Vaxneuvance, ACIP 2021, SBIm 2024",
        "fonte_oficial_id": "FONTE002",
        "ultima_atualizacao": "2024-01-01",
        "responsavel_pela_curadoria": "VacinaFácil AI — dados ACIP/SBIm",
        "observacoes_internas": "PCV20 (Prevnar 20) está em registro no Brasil; quando disponível, pode substituir a sequência PCV15+PPV23 em adultos",
    },
}


def main():
    print(f"\n🌿 VacinaFácil AI — Enriquecendo {len(ATUALIZACOES)} vacinas\n")
    atualizadas = 0
    erros = 0

    for vacina_id, campos in ATUALIZACOES.items():
        try:
            supabase.table("vacinas").update(campos).eq("id", vacina_id).execute()
            nome = campos.get("fabricante_laboratorio", "")
            print(f"   ✅ {vacina_id} enriquecida ({len(campos)} campos)")
            atualizadas += 1
        except Exception as e:
            print(f"   ❌ {vacina_id}: ERRO — {e}")
            erros += 1

    print(f"\n{'='*50}")
    print(f"✅ Atualizadas: {atualizadas} | Erros: {erros}")
    print("="*50)
    print("\nPróximo passo: python gerar_embeddings.py (para reindexar com conteúdo enriquecido)")


if __name__ == "__main__":
    main()
